# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1f76bbbd882c8fd484333dd700b8969114d2633dc7afc164119ce1a7f637e2d587c1b789beeac520bddc39a8a4ee396009792fb24cb69013cdd7a5ef548dcf8

test:
  secret_key_base: afc4ae517ac5e75aa1bc35ed64a6d136622d60fd5e1c91aa3dd3ba224b1724f6576ddd4a326d583e78de32d3981b329cb8b13d6d0b07fc8d17e337e501872560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
